contact: http://www.ucl.ac.uk/research-it-services/partner-with-us

title: "An introduction to research programming with Python"
short: Programming

defaults:
  - scope: {path: ""}
    values: {layout: default}

crumbs:
  - link: http://www.ucl.ac.uk/ISD
    text: ISD
  - link: http://www.ucl.ac.uk/isd/services
    text: Our Services
  - link: http://www.ucl.ac.uk/isd/services/research-it
    text: Research IT
  - link: http://www.ucl.ac.uk/isd/services/research-it/training
    text: Training

baseurl: /doctoral-programming-intro

markdown: redcarpet
redcarpet:
  extensions: ["strikethrough","tables"]
exclude:
  - vendor/
  - Gemfile
  - Gemfile.lock
